id = "graphcal"
name = "Graphcal"
version = "0.0.4"
schema_version = 1
authors = ["shunichironomura"]
description = "Graphcal language support for Zed"
repository = "https://github.com/graphcal-lang/zed-graphcal"

[grammars.graphcal]
repository = "https://github.com/graphcal-lang/tree-sitter-graphcal"
rev = "3e5d0d0145baf8fcf91546747d1fabbc236eacd7"

[language_servers.graphcal-lsp]
name = "Graphcal LSP"
language = "Graphcal"
