id = "graphcal"
name = "Graphcal"
version = "0.0.7"
schema_version = 1
authors = ["shunichironomura"]
description = "Graphcal language support for Zed"
repository = "https://github.com/graphcal-lang/zed-graphcal"

[grammars.graphcal]
repository = "https://github.com/graphcal-lang/tree-sitter-graphcal"
rev = "2428ea60efc0cd2a6301e6c2ab3004ef84448f8e"

[language_servers.graphcal-lsp]
name = "Graphcal LSP"
language = "Graphcal"
